### ISSUE TITLE
Plugin Failure? 

### ISSUE THREAD

**Issue by EHSchmitt4395** [jaysonsantos/kustomize-sops-rs#17]
I've installed per instructions - other plugins i have in same plugin direc work 

sh-3.2# kustomize version
{Version:v4.1.1+ksops.v2.5.5 GitCommit:v4@v4.1.1 BuildDate:2021-06-16T17:07:30Z GoOs:darwin GoArch:amd64}

sops -v
sops 3.7.1 (latest)

```
kustomize build  --enable-alpha-plugins dev
Error:
   0: did not find expected <document start> at line 2 column 1
   1: did not find expected <document start> at line 2 column 1

Location:
   src/lib.rs:102

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: backtrace::backtrace::trace::hfdb317fe0acf29d5
      at <unknown source file>
   2: backtrace::capture::Backtrace::new::ha4ac22ac86613b38
      at <unknown source file>
   3: color_eyre::config::HookBuilder::install::{{closure}}::hca0fe23ddfd87ada
      at <unknown source file>
   4: eyre::capture_handler::hbec0923374db4043
      at <unknown source file>
   5: kustomize_sops::generate_data_field::h4b73c6b6b3cbaed0
      at <unknown source file>
   6: kustomize_sops::process_map::h0e1a58bd64d1878e
      at <unknown source file>
   7: kustomize_sops::main::hf23f66c01a776afd
      at <unknown source file>
   8: std::sys_common::backtrace::__rust_begin_short_backtrace::h8f16c9dd1674e562
      at <unknown source file>
   9: std::rt::lang_start::{{closure}}::hdde7b148d28ba8fc
      at <unknown source file>
  10: std::rt::lang_start_internal::hd0c760d47f593c0a
      at <unknown source file>
  11: _main
      at <unknown source file>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Error: accumulating resources: accumulation err='accumulating resources from 'configmaps/': '/SANITIZEDPATH/dev/configmaps' must resolve to a file': recursed accumulation of path '/SANITIZEDPATH/dev/configmaps': failure in plugin configured via /tmp/kust-plugin-config-087874529; exit status 1: exit status 1
```

**Comment by EHSchmitt4395** [comment]
worth noting the configmap is an encrypted ini file. When i re encrypt as a yaml i get a different error:
```
The application panicked (crashed).
Message:  not yet implemented: Implement mapping
Location: src/lib.rs:117

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: backtrace::backtrace::trace::hfdb317fe0acf29d5
      at <unknown source file>
   2: backtrace::capture::Backtrace::new::ha4ac22ac86613b38
      at <unknown source file>
   3: <color_eyre::config::PanicPrinter as core::fmt::Display>::fmt::h39a886dee9700092
      at <unknown source file>
   4: core::fmt::write::h94ae1e793baa7a00
      at <unknown source file>
   5: <std::io::stdio::Stderr as std::io::Write>::write_fmt::he133b7c866e4cd7d
      at <unknown source file>
   6: std::io::stdio::_eprint::h1d62671f72a093e6
      at <unknown source file>
   7: color_eyre::config::install_panic_hook::{{closure}}::h3518814607ca338f
      at <unknown source file>
   8: std::panicking::rust_panic_with_hook::hc36596b4257bea99
      at <unknown source file>
   9: std::panicking::begin_panic_handler::{{closure}}::h49e5ddc3f21ca2fb
      at <unknown source file>
  10: std::sys_common::backtrace::__rust_end_short_backtrace::h9bd32c9ad3fad18f
      at <unknown source file>
  11: _rust_begin_unwind
      at <unknown source file>
  12: std::panicking::begin_panic_fmt::hc5bc7b154cdecca6
      at <unknown source file>
  13: kustomize_sops::generate_data_field::h4b73c6b6b3cbaed0
      at <unknown source file>
  14: kustomize_sops::process_map::h0e1a58bd64d1878e
      at <unknown source file>
  15: kustomize_sops::main::hf23f66c01a776afd
      at <unknown source file>
  16: std::sys_common::backtrace::__rust_begin_short_backtrace::h8f16c9dd1674e562
      at <unknown source file>
  17: std::rt::lang_start::{{closure}}::hdde7b148d28ba8fc
      at <unknown source file>
  18: std::rt::lang_start_internal::hd0c760d47f593c0a
      at <unknown source file>
  19: _main
      at <unknown source file>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
Error: accumulating resources: accumulation err='accumulating resources from 'configmaps/': '/SANITIZEDPATH /dev/configmaps' must resolve to a file': recursed accumulation of path '/SANITIZEDPATH/dev/configmaps': failure in plugin configured via /tmp/kust-plugin-config-054117889; exit status 101: exit status 101
```

**Comment by EHSchmitt4395** [comment]
also important to note im using GCP for keystore with sops... tests work, is this only compatible with gpg?  Thanks for the help !

**Comment by EHSchmitt4395** [comment]
i got tests to work with gcp key on yaml -- is ini unsupported?  :(

**Comment by jaysonsantos** [comment]
hey there, i've implemented only YAML for now.
would you mind sharing the anonymized version of the YAML you are using? with it I can write a test to avoid any regression.
from the looks of it, it failed to parse it, but to know better i'd have to check it

**Comment by jaysonsantos** [comment]
sorry, I misread it.
you could make the ini an entry of the yaml but you would lose the ability to encrypt only the values.
but yes the parsing error was because it was trying to parse the ini as yaml

**Comment by EHSchmitt4395** [comment]
gotcha ! And thanks for such a quick reply! Curious what you mean by ini as an entry of the yaml? Any elaboration would be appreciated! Do you mean convert the ini to yaml or ?

**Comment by jaysonsantos** [comment]
hey @EHSchmitt4395 sorry to leave you hanging there, i meant something like this
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
data:
  my.ini: |
    [myapp]
    test-key = test-value
    
```
but sops would encrypt the whole data inside `my.ini` and you would not be able to see the keys in plain text like `test-key`
so encrypting the above would be like this
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: myapp
data:
    my.ini: ENC[AES256_GCM,data:3quS5ZxUlBko9NYduFZoC7FNKDjuq1TjlLg0SXJO,iv:0bL0eWbfTgmGI4xVu8PJotMcNO9nIVJIcqgvKlWOSKY=,tag:Mldj7nT0Hq3Z6/ah2EuaDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVTBDai9KWjNnNHRISkl4
            N3ppMXp4RkZDU2hUR2hJSjlCRldtU2I2TFFNCk9VVEJzTG56azJmRlF5TmlOT1dl
            cHZCK0Y0T3FRUkxGbG1VQklmZHk5OGsKLS0tIGtIbHcxNEJDeXQ4OEtmOEN5Y3RS
            cHRDQ2V5MnR6bXh4Y0liaURjc2ZHd0UKH5oMHCKGPqOYqxfntCVB+qfsOARgF3wL
            vWFjw4fEjnfqrLI+ph+7cAR2e7vI/BQzJ2waCwla84JQeNWcGbs1GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-08-12T09:10:40Z"
    mac: ENC[AES256_GCM,data:drgvrROxgwGOxjf0mE5Z8jCrCkNEL6XS3vUwM7Mx8iGzbMLhU3+uVmR7X/brdXaticZHsJbeDL4oCaYyHHsjaxYCMqlpELKOIv0U6Mwe2qozh+kOKi7GhVvhwjD4A2YBtXAasOJ5UnScn983NYn71R+8beTVrhWDYQG2YokKZcA=,iv:oJZVRcVUYSJMXMsPIrRKT66NfmOFJEmOV0ywD055iv0=,tag:bmXBt6CUy5ObKf4C/PkVsg==,type:str]
    pgp: []
    encrypted_regex: my[.]ini
    version: 3.7.1
```
